spring:
  application:
    name: EmoDiary
  # 개발용 설정
  datasource:
    url: jdbc:mysql://emodiary.duckdns.org:3306/emodiary?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: emodiaryback
    password: Fiveguysback12$
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none  # 개발 환경에서는 update, 운영 환경에서는 validate 권장
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  redis:
   host: emodiary.duckdns.org
   port: 6379
   password: flsdl@qkqn7
   database: 0
   timeout: 60000
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    disable-swagger-default-url: true
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.fiveguysburger.emodiary
